name: Admin Build

on:
  pull_request:
    paths:
      - 'apps/admin/**'
    branches: [main, dev]

jobs:
  build:
    uses: sisques-labs/workflows/.github/workflows/web-build.yml@main
    with:
      app_path: 'apps/admin'
      app_name: 'Admin App'
      node_version: '24'
      run_lint: true
      run_test: true
      build_command: 'build'
    secrets: inherit
