name: API Build

on:
  pull_request:
    paths:
      - 'apps/api/**'
    branches: [main, dev]

jobs:
  build:
    uses: sisques-labs/workflows/.github/workflows/api-build.yml@main
    with:
      app_path: 'apps/api'
      app_name: 'API'
      node_version: '24'
      run_lint: true
      run_test: true
      build_command: 'build'
    secrets: inherit
